version: '3'
services:
  user_api:
    build: ./user/
    network_mode: "host"
  collection_points_api:
    build: ./collectionPoints/deployment/
    depends_on:
      - user_api
    network_mode: "host"
  collection_api:
    build: ./Collections/
    network_mode: "host"