server:
  port: 8080
spring:
  application:
    name: "collectionPoint"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/botellas_amor"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:5000/user/v1/create/user"
cors:
  allowed-origins: "*"
